[package]
name = "rust_library"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
jni = "0.21.1"
log = { version = "0.4", features = ["std"] }
android_logger = "0.14.1"
