[package]
name = "rust_library"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
jni = "0.21.1"
log = { version = "0.4", features = ["std"] }
android-logd-logger = "0.4.4"
jni-sys = "0.4.0"
android_logger = "0.14.1"
ndk-sys = "0.6.0"
ndk = "0.9.0"